### ISSUE TITLE
external dependencies management?

### ISSUE THREAD

**Issue by niXman** [omercsp/simple-build-system#1]
hello!

do you plan to implement smth like external dependencies management?
for example: a possibility do download some files/archives, versioned repos like git/etc

I think it would be great!

best!

**Comment by omercsp** [comment]
I'm not sure I understand what "smth like external dependencies" are, but if I got it right, what you want is somewhat beyond the scope of this project, which aims to be a (simple) build system.

SBS does provide, however, pre-build and post-build hooks, where you can download things, update repos and whatnot before (and after) the build starts. What exactly is being done in these steps is completely up to the user to decide.

Does this answer your question? (I'm not sure I understood your meaning).

**Comment by niXman** [comment]
I mean a way that will allow in the list of sources to refer to external files/projects.

for example:
```
MODULE_SRCS := file1.c file2.c $(download https://github.com/niXman/tiny-args.git, tiny-args.hpp) file3.c 
```
with this example I want to show an example of how a usual git clone without a separate build step, would be a very convenient feature!

what do you think about that?

**Comment by omercsp** [comment]
OK, I see what you mean, but my answer, I'm afraid, remains the same - this is beyond the scope of what this project tries to achieve. It is even somewhat against the ideas behind it - a minimal and bare build system that is easy to setup (at least for basic usage), very light weight with minimal dependencies.

This doesn't mean you can't use SBS and have your desired feature (or any other) working together.  SBS is rather easy to extend if you know what you're doing. A small Makefile function definition like this:
```
define Download
	$(shell put-whatever-you-want-in-here-maybe-a-shell-script $(1) $(2))
endef
```
can get you sorted out. Assuming you want to use this all over your SBS modules, you can place your `Download` function in a file, say `my_build_tools.inc.mk`, and have you make files looking like this (note the use of `call`):
```
include my_build_tools.inc.mk # <-- This is where the download fucntion is defined
MODULE_SRCS := file1.c file2.c $(call download https://github.com/niXman/tiny-args.git, tiny-args.hpp) file3.c
...
include module.inc.mk
```

Now you'll have a nice tool ready to be used again in any SBS based project (maybe in other systems as well).

I hope this helps; let me know what you think.

**Comment by niXman** [comment]
> but my answer, I'm afraid, remains the same - this is beyond the scope of what this project tries to achieve.

sure, I got it. no problem!
it was just an idea.

thank you!
